### ISSUE TITLE
all methods must have a name of at least 3 characters

### ISSUE THREAD

**Issue by TomCJones** [w3c/did-resolution#11]
I plan to build a resolver which will reserve 2 character codes for country codes which can only be claimed the the country itself.

**Comment by peacekeeper** [comment]
Since this is a proposed syntax rule rather than directly related to DID Resolution, could you raise it on the main DID spec repo (https://github.com/w3c-ccg/did-spec/) instead and close it here?

**Comment by TomCJones** [comment]
i can do that at some later point. I do look at this as a resolution issue myself in that i will chose not to resolve those methods.

**Comment by peacekeeper** [comment]
@TomCJones looking at this again after a while, I continue to believe that this is a DID Core related issue, rather than DID Resolution. I noticed that you opened and closed a similar issue in https://github.com/w3c-ccg/did-spec/issues/160. Would you be okay with closing this here as well (and potentially open a new one in DID Core if you think this topic is still relevant)?

**Comment by pchampin** [comment]
This was discussed during the [did meeting on 10 October 2024](https://www.w3.org/2024/10/10-did-minutes.html#ca33).

<details><summary><i>View the transcript</i></summary>

<h3>DID Resolution Issue/PR Processing</h3>
<p><cite>burn:</cite> Contact the chairs if anyone would suggest an improvement</p>
<p><cite>markus_sabadello:</cite> let's start with new issues</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3Apending-close" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3Apending-close</a></p>
<p><cite>markus_sabadello:</cite> first with pending close issues</p>
<p><cite>burn:</cite> note that, in the agenda email, we listed these issues.<br>
<span>… We'll be using this process until the end of the thursday meeting to object to the close.</span></p>
<p><cite>&lt;TallTed&gt;</cite> I strongly recommend such searches be ordered by "least recently updated" to keep the churn active, e.g., <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3Apending-close+sort%3Aupdated-asc" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3Apending-close+sort%3Aupdated-asc</a></p>
<p><cite>burn:</cite> the point is, we'll review these quickly today, but the expectation is that you are too look for these in the agenda and speak up or comment in the issue if you have an objection<br>
<span>… so we will not be spending time unless there is a concern (as a general rule)</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/57" rel="noopener noreferrer">w3c/<wbr>did-resolution#57</a></p>
<p><cite>markus_sabadello:</cite> Proposal to rename one of the resolution functions<br>
<span>… Resolve and ResolveStream</span><br>
<span>… This issue is a proposal to rename ResolveStream. That's already happened. I posted a comment 2 weeks ago. No further discussion</span></p>
<p><cite>burn:</cite> any objections to closing?</p>
<p><cite>markus_sabadello:</cite> I'll close them after the call</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/30" rel="noopener noreferrer">w3c/<wbr>did-resolution#30</a></p>
<p><cite>markus_sabadello:</cite> Issue 30, several years old. Has to do with dereferencing discussion at TPAC<br>
<span>… "The result of dereference can be a DID document, but it can also be something else"</span><br>
<span>… Looking at this issue after a long time, I think the current specification addresses this. I see 3 thumbs up to that comment.</span><br>
<span>… So, if no objections, we'll be closing this.</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/29" rel="noopener noreferrer">w3c/<wbr>did-resolution#29</a></p>
<p><cite>markus_sabadello:</cite> also several years old, about the definition of the term did resolver.<br>
<span>… In the current specification, both terms are defined formally in terminology section. Also two thumbs up.</span><br>
<span>… Any objections?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/21" rel="noopener noreferrer">w3c/<wbr>did-resolution#21</a></p>
<p><cite>markus_sabadello:</cite> Issue 21 about removing the term DID Reference from DID core to DID Resolution.<br>
<span>… I think this is now obsolete. We don't use that term in any spec.</span><br>
<span>… Same discussion was also in did-core, which was closed. So I think this one can be as well.</span><br>
<span>… Any objections?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/11" rel="noopener noreferrer">w3c/<wbr>did-resolution#11</a></p>
<p><cite>markus_sabadello:</cite> All methods must have a name of at least three characters.<br>
<span>… This seems like a DID Core issue, not in DID Resolution</span><br>
<span>… Similar issue in DID-core, which has also been closed.</span><br>
<span>… For all of these issues, it seems straightforward to close them.</span><br>
<span>… Since they are older issues, we may not be getting engagement from the initial poster, but unless there are objections, seems like we should close</span></p>
<p><cite>decentralgabe:</cite> If we mark it pending close and give it a week, that would address the older participants</p>
<p><cite>burn:</cite> requirements vary from group to group. In past groups, we've made the point to actively reach out by email and ask for engagement. Then you can comment that in the issue.<br>
<span>… so ping in the issue, then email, then document that email in the issue.</span><br>
<span>… That let's us show we've done what we can to address the concerns of the original poster</span><br>
<span>… For these, I think we're good, but going forward that's a nice improvement to our process</span></p>
<p><cite>burn:</cite> you have 10 more minutes if you like</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-resolution/<wbr>issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22</a></p>
<p><cite>markus_sabadello:</cite> one other thing. A few issues are tagged as "Good First Issue"<br>
<span>… Two of them have been assigned. One has not.</span><br>
<span>… These are a good way to contribute, especially if you might not be familiar with deeper technical issues.</span><br>
<span>… We'll try to find more like that and encourage PRs</span><br>
<span>… A few that might be ready to close</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/23" rel="noopener noreferrer">w3c/<wbr>did-resolution#23</a></p>
<p><cite>markus_sabadello:</cite> Issue 23 is about result of dereferencing</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Looking at the backlog. There is an opportunity here to make a distinction -- how we talk about a DID with and without a trailing slash... but I don't know if that helps us. I need to look at this in more detail, it's five years old, we can close it, if problem still exists, we can raise a new issue again.</p>
<p><cite>&lt;manu&gt;</cite> markus_sabadello: I think this might be obsolete by now?</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Yeah, sounds like it might be.</p>
<p><cite>&lt;manu&gt;</cite> markus_sabadello: We will have until next call to look at it or raise a new issue if this comes back.</p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: Sounds good to me.</p>
<p><cite>manu:</cite> I'm wondering what is the ... I'm fine with closing it. I'm wondering where did we land?<br>
<span>… the response from a resolver is a resolution result, which might contain a did document?</span><br>
<span>… Is that where we landed?</span></p>
<p><cite>markus_sabadello:</cite> that's right the resolution response might contain a did document, but dereferencing might return something else</p>
<p><cite>manu:</cite> i think it's already addressed (as opposed to an older issue that isn't valid)</p>
<p><cite>markus_sabadello:</cite> this was from when we didn't have a did resolution result, we were just returning DID documents<br>
<span>… That has been addressed</span></p>
<p><cite>&lt;JoeAndrieu&gt;</cite> +1</p>
<p><cite>manu:</cite> +1</p>
<p><cite>markus_sabadello:</cite> also to be aware of, from discussions at TPAC, when we talked about path, query, and fragment parts.<br>
<span>… we talked about different patterns in the past and how much of that should be in the resolution spec itself or in did core, or in both.</span><br>
<span>… If people come up with certain features that use the path or query string, how does that fit in and where does it get specified?</span></p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/85" rel="noopener noreferrer">w3c/<wbr>did-resolution#85</a></p>
<p><cite>markus_sabadello:</cite> There are two open issues for new DID parameters with certain functionality</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/issues/90" rel="noopener noreferrer">w3c/<wbr>did-resolution#90</a></p>
<p><cite>markus_sabadello:</cite> The first introduces version-type the second XYZ as parameters<br>
<span>… Please comment about where these should go and whether or not it should be did-method-specific or standardized across methods</span></p>
<p><cite>burn:</cite> ok, you have about another 5 minutes if you'd like</p>
<p><cite>markus_sabadello:</cite> ok. I'm wondering if we can merge that pull request</p>
<p><cite>&lt;markus_sabadello&gt;</cite> <a href="https://github.com/w3c/did-resolution/pull/89" rel="noopener noreferrer">w3c/<wbr>did-resolution#89</a></p>
<p><cite>markus_sabadello:</cite> or if anyone has new thoughts about the discussion we had about primary resource and secondary resource<br>
<span>… there is an open PR where I tried to improve the headings</span><br>
<span>… to help with that. I'm wondering if people have opinions.</span><br>
<span>… I would actually prefer not to merge because it makes the headings longer</span><br>
<span>… But the algorithm talks about dereferencing the primary resource and secondary resource</span><br>
<span>… This PR adds explanation to the headings</span></p>
<p><cite>manu:</cite> I think it is unfortunate that the initial wording was primary and secondary resource, as that is so abstract it is confusing.<br>
<span>… +1 to comment about section titles get hard</span></p>
<p><cite>&lt;TallTed&gt;</cite> +1 to manu's suggestion</p>
<p><cite>manu:</cite> maybe we can call it derereferencing a DID? or a #fragment<br>
<span>… +1 to not merge this, but maybe we can have did document and fragment as the terms</span></p>
<p><cite>markus_sabadello:</cite> there is something that right now is called a primary resource.<br>
<span>… there needs to be a name for what you get when you dereference the did document</span><br>
<span>… For example, dereferencing the DID URL resource may be a better phrase</span></p>
<p><cite>manu:</cite> yes. that was my thinking. Name the types of things you can dereference.<br>
<span>… A use case where you get a DID Document. A case where you dereference a fragment in a resource. And a third case where it's neither of those.</span><br>
<span>… Related Resource? (Not suggesting that, but if we name it, it will help)</span></p>
<p><cite>markus_sabadello:</cite> this needs to be extensible. we can't imaging all the things they dereference to.<br>
<span>… but i think we can use better terms than Primary &amp; Secondary. I'll try to do that.</span></p>
<p><cite>&lt;manu&gt;</cite> JoeAndrieu: I would like to try my hand at writing this PR, don't know when I'm going to get to it, but want to help.</p>

<hr /></details>
