### ISSUE TITLE
About resolving protocol question

### ISSUE THREAD

**Issue by zhanb** [w3c/did-resolution#60]
Hi, I've been following did for a long time, I want to know besides HTTP (s) + JSON, is there any plan to support COAP + CBOR for did resolution ?

**Comment by peacekeeper** [comment]
Coming back to this issue after a while...

I think there are currently no plans in the DID WG to specify a binding other than the [HTTP(S) Binding](https://w3c.github.io/did-resolution/#bindings-https).

Regarding CBOR, there is a Note document that defines a CBOR representation for DID documents: https://www.w3.org/TR/did-cbor-representation/

Maybe this answers the question?

**Comment by mccown** [comment]
This came up in a meeting today, so I started looking into it.  CoAP (Constrained Application Protocol; RFC 7252) is a UDP protocol that is used in home automation where packet sizes need to be small.  

As @peacekeeper mentioned, the DID WG doesn't currently have plans to work on this.  If there were an uptick in IoT DID users, the group might consider it.  In the meantime, the Matrix.org Foundation has provided source for a CoAP <-> HTTP proxy (https://github.com/matrix-org/coap-proxy).  This should let IoT developers convert between the 2 protocols in order to use DIDs in those types of IoT environments.

Great question, but isn't currently on our roadmap.

**Comment by peacekeeper** [comment]
Closing after today's DID WG meeting.
